### ISSUE TITLE
os x problem (ERROR: GetDirectory: Error getting plugin://)

### ISSUE THREAD

**Issue by sopi20** [beam/repository.beam.xbmc-addons#30]
Na os x (skusane na 10.10 a 10.11) je problem - pri pokuse o vyhladanie/download titulkov vypise chybu, v logu je nasledovne:

22:19:21 T:123145318633472   DEBUG: StartScript - calling plugin Titulky.com('plugin://service.subtitles.titulky.com/','18','?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech')
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(18, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): start processing
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(18, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): the source file to load is "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py"
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(18, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): setting the Python path to /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(18, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): entering source directory /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(18, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): instantiating addon using automatically obtained id of "service.subtitles.titulky.com" dependent on version 2.14.0 of the xbmc.python api
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py", line 29, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/TitulkyClient.py", line 9, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/usage_stats.py", line 10, in <module>
22:19:21 T:123145318633472   ERROR: GetDirectory - Error getting plugin://service.subtitles.titulky.com/?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech
22:19:21 T:123145313726464   DEBUG: StartScript - calling plugin Titulky.com('plugin://service.subtitles.titulky.com/','19','?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech')
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(19, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): start processing
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(19, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): the source file to load is "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py"
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(19, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): setting the Python path to /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(19, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): entering source directory /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com
22:19:21 T:123145304526848   DEBUG: CPythonInvoker(19, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): instantiating addon using automatically obtained id of "service.subtitles.titulky.com" dependent on version 2.14.0 of the xbmc.python api
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py", line 29, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/TitulkyClient.py", line 9, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/usage_stats.py", line 10, in <module>
22:19:21 T:123145313726464   ERROR: GetDirectory - Error getting plugin://service.subtitles.titulky.com/?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech

Obdobne sa sprava pre edna.cz (t.j. problem je asi generickejsi a nie viazany na konkretny service)

**Comment by beam** [comment]
chm, ted sem to ozkousel na 10.10.4 a slape, tak to se bude blbe ladit..
Kodi 15.1?

**Comment by sopi20** [comment]
Jo, presne tak, Kodi 15.1.

P.

**Comment by beam** [comment]
Hm, jen tak cvicne zkus smaznout titulky.com:
rm -r ~/Library/Application\ Support/Kodi/addons/service.subtitles.titulky.com
rm -r ~/Library/Application\ Support/Kodi/addons/packages/service.subtitles.titulky.com-*.zip
a potom nainstalovat znovu z 
https://github.com/beam/repository.beam.xbmc-addons/raw/gh-pages/packages/service.subtitles.titulky.com/service.subtitles.titulky.com-1.2.1.zip

**Comment by beam** [comment]
Ale nasel jsem si drobnou chybku :]
Mas v ~/Library/Application\ Support/Kodi/addons/ adresar script.module.simplejson ?

**Comment by sopi20** [comment]
Skusil som, nepomohlo :(

23:21:54 T:140735231262720   DEBUG: New Service [service.subtitles.titulky.com]
23:21:54 T:123145305600000   DEBUG: StartScript - calling plugin Titulky.com('plugin://service.subtitles.titulky.com/','4','?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech')
23:21:54 T:123145302839296   DEBUG: CPythonInvoker(4, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): start processing
23:21:54 T:123145302839296   DEBUG: CPythonInvoker(4, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): the source file to load is "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py"
23:21:54 T:123145302839296   DEBUG: CPythonInvoker(4, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): setting the Python path to /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com:/Applications/Kodi.app/Contents/Libraries:/Applications/Kodi.app/Contents/Libraries/lib/python26.zip:/Applications/Kodi.app/Contents/Libraries/lib/python2.6:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-darwin:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/plat-mac/lib-scriptpackages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-tk:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-old:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/lib-dynload:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages:/Applications/Kodi.app/Contents/Libraries/lib/python2.6/site-packages/PIL
23:21:54 T:123145302839296   DEBUG: CPythonInvoker(4, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): entering source directory /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com
23:21:54 T:123145302839296   DEBUG: CPythonInvoker(4, /Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py): instantiating addon using automatically obtained id of "service.subtitles.titulky.com" dependent on version 2.14.0 of the xbmc.python api
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/service.py", line 29, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/TitulkyClient.py", line 9, in <module>
                                              File "/Users/sopi20/Library/Application Support/Kodi/addons/service.subtitles.titulky.com/resources/lib/usage_stats.py", line 10, in <module>
23:21:54 T:123145305600000   ERROR: GetDirectory - Error getting plugin://service.subtitles.titulky.com/?action=search&languages=Czech%2cEnglish%2cSlovak&preferredlanguage=Czech

P.

**Comment by sopi20** [comment]
Nemam, v tom foldri mam len nasledovne:

drwxr-xr-x   8 sopi20  staff  272 Oct  2 23:19 .
drwxr-xr-x   9 sopi20  staff  306 Oct  2 14:05 ..
drwxr-xr-x   7 sopi20  staff  238 Oct  2 14:05 metadata.themoviedb.org
drwxr-xr-x   5 sopi20  staff  170 Oct  2 23:19 packages
drwxr-xr-x   4 sopi20  staff  136 Oct  2 14:26 repository.beam.xbmc-addons
drwxr-xr-x   8 sopi20  staff  272 Oct  2 14:28 service.subtitles.edna.cz
drwxr-xr-x   8 sopi20  staff  272 Oct  2 23:19 service.subtitles.titulky.com
drwxr-xr-x  10 sopi20  staff  340 Oct  2 14:05 service.xbmc.versioncheck

P.

**Comment by beam** [comment]
Aha, tak zkusime upgrade..
https://github.com/beam/repository.beam.xbmc-addons/raw/gh-pages/packages/service.subtitles.titulky.com/service.subtitles.titulky.com-1.2.2.zip

**Comment by sopi20** [comment]
Teraz to uz funguje jedna radost :)

Dakujem

P.
